# ABOUTME: GitHub Actions workflow for automated Docker image building and publishing
# ABOUTME: Builds and pushes Docker images to GitHub Container Registry on main branch pushes

name: Docker Build and Publish

on:
  push:
    branches: [ main ]

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository's code
      uses: actions/checkout@v4
      
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./base
        file: ./base/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/sd-base:latest
          ghcr.io/${{ github.repository_owner }}/sd-base:cuda-12.2